2024-08-01
Added dependencies and reword printed comments.

diff --git a/github-clone-all b/github-clone-all
--- a/github-clone-all
+++ b/github-clone-all
@@ -1,5 +1,6 @@
 #!/bin/bash
 # github-clone-all 2024-07-31
+# Dependencies: which curl jq git findutils bash coreutils ncurses sudo
 # Clones all github authors non forked repos.
 # Usage ie: github-clone-all [author]
 # URL ie: author 'Cody-Learner' of https://github.com/Cody-Learner
@@ -11,14 +12,14 @@ OFF=$(tput sgr0)
 author="${1-}"
 
 if	[[ ! -v 1 ]]; then									# Print message if
-	printf '\f%s\n' "${BC}  Usage:${OFF} github-clone-all [author]"				# missing argument
-	printf '%s\f\n' "${BC}  ie   :${OFF} github-clone-all Cody-Learner"
+	printf '\f%s\n' "${BC} Error missing${OFF} Usage: github-clone-all [author]"			# missing argument
+	printf '%s\f\n' "${BC}  author arg${OFF}   ie: github-clone-all Cody-Learner"
 	exit
 fi
 
-if	! which curl jq git xargs &>/dev/null; then						# Check/install deps
+if	! which which curl jq git xargs bash printf tput sudo git &>/dev/null; then		# Check/install deps
 	printf '\f%s\f\n' "${BC}  Checking/Installing missing dependencies. ${OFF}"
-	sudo pacman -S --needed which curl jq git findutils
+	sudo pacman -S --needed which curl jq git findutils bash coreutils ncurses sudo
 fi
 	printf '\f%s\f\n' "${BC}  Cloning repos.... ${OFF}"
 
